name: Custom Workflow Dispatch

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your username'
        required: true
        default: 'user'
      favorite_color:
        description: 'Enter your favorite color'
        required: true
        default: 'blue'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      username: ${{ steps.get-inputs.outputs.username }}
      favorite_color: ${{ steps.get-inputs.outputs.favorite_color }}
    steps:
      - name: Get inputs
        id: get-inputs
        run: |
          echo "username=${{ github.event.inputs.username }}"
          echo "favorite_color=${{ github.event.inputs.favorite_color }}"
          echo "::set-output name=username::${{ github.event.inputs.username }}"
          echo "::set-output name=favorite_color::${{ github.event.inputs.favorite_color }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      GREETING: ${{ steps.greet-user.outputs.greeting }}
    steps:
      - name: Greet user
        id: greet-user
        run: |
          USERNAME="${{ needs.job1.outputs.username }}"
          COLOR="${{ needs.job1.outputs.favorite_color }}"
          GREETING="Hello, $USERNAME! I see your favorite color is $COLOR."
          echo "::set-output name=greeting::$GREETING"
        env:
          USERNAME: ${{ needs.job1.outputs.username }}
          COLOR: ${{ needs.job1.outputs.favorite_color }}

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo greeting message
        run: echo ${{ needs.job2.outputs.GREETING }}
